title: The KvX Directive
description: A signal archive maintained by KvXbyte.
baseurl: "" 
url: "https://kvxbyte.github.io"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false

minimal_mistakes_skin: "dark"

# Navigation bar items
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/

# Header pages (for layout compatibility)
header_pages:
  - index.md
  - _pages/about.md

# Optional author info for footers or meta
author:
  name: "KvXbyte"
  avatar: "/assets/images/avatar.png"
  bio: "Signal analyst. Defender of logs. Speaker of packet truths."
