title: The KvX Directive
description: KvXbyte’s cybersecurity archive — structured logs, analysis, and operations.
baseurl: ""
url: "https://kvxbyte.github.io"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      read_time: false

minimal_mistakes_skin: "dark"

# Nav items
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/

header_pages:
  - _pages/index.md
  - _pages/about.md

  avatar: "/assets/images/avatar.png"
  bio: "Signal analyst. Defender of logs. Speaker of packet truths."

# Trigger rebuild
