title: The KvX Directive
description: A signal archive maintained by KvXbyte.
baseurl: ""
url: "https://kvxbyte.github.io"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false

minimal_mistakes_skin: "dark"

# Navigation
header_pages:
  - index.md

# Optional social footer
author:
  name: "KvXbyte"
  avatar: "/assets/images/avatar.png"
  bio: "Signal analyst. Defender of logs. Speaker of packet truths."
